// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw4Fr4mXpbM8hmBSy6YqDIvjCd1D0AIcc',
    appId: '1:207816454655:web:a02f5abc0850450a71b7ca',
    messagingSenderId: '207816454655',
    projectId: 'loginauthentication-b56f6',
    authDomain: 'loginauthentication-b56f6.firebaseapp.com',
    storageBucket: 'loginauthentication-b56f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmpmEU0C6lRpX3h1ZtTDSFyqDWAGle4gY',
    appId: '1:207816454655:android:6d8e6f7a636834fd71b7ca',
    messagingSenderId: '207816454655',
    projectId: 'loginauthentication-b56f6',
    storageBucket: 'loginauthentication-b56f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfDuYUF6R0YFobBJyouCbf0E7822X7z6Q',
    appId: '1:207816454655:ios:128eee5fae30a1a671b7ca',
    messagingSenderId: '207816454655',
    projectId: 'loginauthentication-b56f6',
    storageBucket: 'loginauthentication-b56f6.appspot.com',
    iosBundleId: 'com.example.loginUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfDuYUF6R0YFobBJyouCbf0E7822X7z6Q',
    appId: '1:207816454655:ios:20485452ba28091371b7ca',
    messagingSenderId: '207816454655',
    projectId: 'loginauthentication-b56f6',
    storageBucket: 'loginauthentication-b56f6.appspot.com',
    iosBundleId: 'com.example.loginUi.RunnerTests',
  );
}
